BlogApp/views/profile.py
import BlogApp
import os
from flask import render_template, request, Blueprint, flash, redirect, url_for
from BlogApp.models import *
from BlogApp.forms import profile_handling, private_message
from BlogApp import db, static
from BlogApp.static import profiles
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename

profile = Blueprint('profile', __name__)

def count_likes(blog_id):
    likers = liked_blog.query.filter_by(blog_id=blog_id).all()
    likes = len(likers)
    return likes
@profile.route("/dashboard", methods=['GET', 'POST']) 
@login_required
def dashboard():
    unread_count = 0
    for i in current_user.profile.received_messages:
        if i.read == False:
            unread_count += 1
    num_blogs = 0
    num_views = 0
    num_likes = 0
    num_comments = 0
    for i in current_user.profile.blogs:
        num_blogs += 1
        num_views += i.views
        num_likes += count_likes(i.id)
        comments = len(Comment.query.filter_by(blog_id=i.id).all())
        num_comments += comments
    num_fixed = len(Fixed.query.filter_by(user=current_user.id).all())
    num_others = len(Other.query.filter_by(user=current_user.id).all())
    return render_template('profile/dashboard.html',num_blogs=num_blogs,num_views=num_views,num_likes=num_likes,num_comments=num_comments,num_fixed=num_fixed,num_others=num_others,unread=unread_count) 

@profile.route("/account", methods=['GET', 'POST']) 
@login_required
def account():
    unread_count = 0
    for i in current_user.profile.received_messages:
        if i.read == False:
            unread_count += 1
    return render_template('profile/account.html',unread=unread_count) 


@profile.route("/personal_blogs", methods=['GET', 'POST']) 
@login_required 
def personal_blogs():
    unread_count = 0
    for i in current_user.profile.received_messages:
        if i.read == False:
            unread_count += 1
    records = Profile.query.filter_by(id=current_user.id).first().blogs.order_by(blog_data.category).all()     
    return render_template('profile/personal_blogs.html', posts=records, count_likes=count_likes,unread=unread_count) 

@profile.route("/liked_blogs", methods=['GET', 'POST'])  
@login_required
def liked_blogs():   
    records = []
    unread_count = 0
    posts_exist = False
    for i in current_user.profile.received_messages:
        if i.read == False:
            unread_count += 1
    liked_posts = liked_blog.query.filter_by(liker_id=current_user.id).all()
    ids = []
    for i in liked_posts:
        ids.append(i.blog_id)
    records=[]
    for i in ids:
        to_add = blog_data.query.filter_by(id=i).first()
        records.append(to_add)
    if len(records) != 0:
        posts_exist = True
    
    return render_template('profile/liked_blogs.html', posts=records,unread=unread_count,posts_exist=posts_exist)   


@profile.route("/ext_profile/<id>", methods=['GET', 'POST'])
@login_required
def ext_profile(id): 
    form = private_message(message='')
    records = Profile.query.filter_by(id=str(id)).first() 
    if records is None:
        flash("No profile with that ID! Please check your URL and try again!", 'red')
        return redirect(url_for('general.your_blogs'))
    elif request.method == 'POST' and form.validate_on_submit():
        message = Message(sender_id=current_user.id,recipient_id=records.id,content=form.message.data,link=str('/ext_profile/'+str(current_user.id)))
        db.session.add(message)
        db.session.commit()
        flash('Message has been sent','green')
        return render_template('profile/ext_profile.html', profile=records,form=form)      
    else:
        return render_template('profile/ext_profile.html', profile=records,form=form) 




@profile.route("/edit_profile", methods=['GET', 'POST'])
@login_required
def edit_profile():
    records = Profile.query.filter_by(id=current_user.id).first()    
    if records is None:
        abort(404)
    else:
        form = profile_handling(name=records.name, job=records.job, location=records.location, description=records.description,img=records.img,user=records,fb=records.fb,ig=records.ig,tw=records.tw)
    
    if request.method == 'POST' and form.validate_on_submit():
        records.name = form.name.data
        records.job = form.job.data
        records.location = form.location.data
        records.description = form.description.data
        if form.fb.data is None:
            records.fb = 'NIL'
        else:
            records.fb = form.fb.data
        if form.ig.data is None:
            records.ig = 'NIL'
        else:
            records.ig = form.ig.data
        if form.tw.data is None:
            records.tw = 'NIL'
        else:
            records.tw = form.tw.data
        f = form.img.data
        if f is not None and type(f) != str:
            filename = secure_filename(f.filename)
            try:
                os.makedirs('BlogApp/static/profiles/'+str(current_user.id)+'/')
            except:
                pass
            f.save(os.path.join('BlogApp', 'static', 'profiles', str(current_user.id),filename))
            records.img = str('/static/profiles/'+str(current_user.id)+'/'+str(filename))
        
        db.session.commit()
        
        
        return redirect(url_for('profile.account'))
    
    return render_template('profile/edit_profile.html', form=form)  
            


@profile.route("/delete_profile", methods=['POST'])         
@login_required 
def delete_profile(): 
    user = Auth.query.filter_by(id=current_user.id).first()
    user.deleted = True
    db.session.commit()
    flash('Successfully deleted profile', 'green')
    return redirect(url_for('auth.logout'))

BlogApp/templates/profile/account.html
{% extends "profile_base.html" %}
{% block title %} Your Account {% endblock %}


{% block body %} 
<div class="bg-white mt-10 shadow overflow-hidden sm:rounded-lg">
    <div class = "items-center p-8">
      <img src = "{{current_user.profile.img}}" class = "realtive z-40 w-30 h-30 object_contain items-center rounded-sm overflow-hidden border-4 border-gray-400 hover:border-gray-300 focus:border-gray-300 focus:outline-none"></img>
    </div>
    <div class="px-4 py-5 pt-0 sm:px-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Your Information
      </h3>
      <p class="mt-1 max-w-2xl text-sm text-gray-500 mb-3">
        Personal details and data.
      </p>
      <a href="/ext_profile/{{current_user.profile.id}}" class="font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
        See what others see.
    </a>
    <br>
    <a href="/reset" class="font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
      Reset password
  </a>
    <br>
    </div>

    <div class="border-t border-gray-200">
      <dl>
        
        <div class="bg-gray-100 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Full name
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            {{current_user.profile.name}}

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
          
        </div>

        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Job
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            {{current_user.profile.job}}

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
        </div>

        <div class="bg-gray-100 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Location
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            {{current_user.profile.location}}

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
        </div>
        
        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Description
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            {{current_user.profile.description}}

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
        </div>

        <div class="bg-gray-100 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Facebook Profile link
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            <a href = {{current_user.profile.fb}}>{{current_user.profile.fb}}</a>

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
          
        </div>

        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Instagram Profile link
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            <a href = {{current_user.profile.ig}}>{{current_user.profile.ig}}</a>

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
        </div>

        <div class="bg-gray-100 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">
            Twitter Profile Link
          </dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 flex items-center justify-between">
            <a href = {{current_user.profile.tw}}>{{current_user.profile.tw}}</a>

            <a href="/edit_profile" class="ml-2 font-medium flex-shrink-0 text-indigo-600 hover:text-indigo-500 text-right">
                Update
            </a>

          </dd>
          
        </div>
        
      </dl>
    </div>
</div>

<div class='py-6 text-right'>	<!--form to delete profile/account-->
  <form action="{{ url_for('profile.delete_profile') }}" method='POST'>
    <input type='submit' value='Delete profile' onclick="return confirm('Are you sure you want to delete your profile?')" class="bg-red-700 hover:bg-red-800 text-white font-bold py-2 px-4 mt-6 mb-0">
                          <!--conformation message-->
  </form>
</div>
  
{% endblock %}

BlogApp/templates/profile/edit_pic.html
{% extends "form_base.html" %}
{% from "_formhelpers.html" import blog_render_field %}

{% block title %}Edit Profile Picture{% endblock %}

{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Welcome to Unveiled</h3>
        <p class="text-gray-600 pt-2">Edit your profile.</p>
    </section>

    <section class="mt-4">
        <form class="flex flex-col" method="POST" action="/edit_pic" enctype="multipart/form-data"> 
            {{ form.csrf_token }}
            {{ blog_render_field(form.img, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Upload</button>
        </form>
    </section>
</main>
{% endblock %}

{% block href1 %}/account{% endblock %}    {% block href_tag1 %}Account{% endblock %}
{% block href2 %}/contact_us{% endblock %}    {% block href_tag2 %}Contact Us{% endblock %}

    

BlogApp/templates/profile/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Pranav Tumminkatti">
	<meta name="description" content="A blogsite">
	<meta name="robots" content="all">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>Edit Profile</title>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
</head>
<body class='m-14 bg-gray-50'>
    <div>
        <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
            <div class="px-4 sm:px-0">
            <h3 class="text-lg font-medium leading-6 text-gray-900">Profile</h3>
            <p class="mt-1 text-sm text-gray-600">
                This information will be displayed publicly so be careful what you share.
            </p>
            </div>
        </div>
        <div class="mt-5 md:mt-0 md:col-span-2">
            <form method="POST" action="{{ url_for('profile.edit_profile') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="shadow sm:rounded-md sm:overflow-hidden bg-white">
                <div class='pl-6 pt-6'>
                    <label class="block text-sm font-medium text-gray-700">
                    Photo
                    </label>
                    <div class="mt-1 flex items-center">
                    <span class="inline-block h-12 w-12 rounded-full overflow-hidden bg-gray-100 mr-3">
                        <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                        </svg>
                    </span>
                    
                {{form.img}}
                    </div>
                </div>

                <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                <div>
                    {{form.description.label(class="block text-sm font-medium text-gray-700")}}
                    <div class="mt-1">
                        {{form.description(class="p-2 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
                    <p class="mt-2 text-sm text-gray-500">
                    Brief description for your profile.
                    </p>
                </div>
                <div class="grid grid-cols-6 gap-6">
                    <div class="col-span-6 sm:col-span-3">
                        {{form.name.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.name(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
    
                    <div class="col-span-6 sm:col-span-3">
                        {{form.job.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.job(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
    
                    <div class="col-span-6 sm:col-span-4">
                        {{form.location.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.location(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
    
                    <div class="col-span-6">
                        {{form.fb.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.fb(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
    
                    <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                        {{form.tw.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.tw(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
    
                    <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                        {{form.ig.label(class="block text-sm font-medium text-gray-700")}}
                        {{form.ig(class="p-1.5 border-gray-300 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border rounded-md")}}
                    </div>
                </div>
                </div>
                <div class="px-4 py-3 bg-gray-100 text-right sm:px-6">
                <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Save
                </button>
                </div>
            </div>
            </form>
        </div>
        </div>
    </div>
    
    </div>
  
  
</body>
</html>

BlogApp/templates/profile/ext_profile.html
{% extends "base.html" %}
{% from "_formhelpers.html" import blog_render_field %}
{% block title %} {{profile.name}} {% endblock %}

{% block body %} 
<body class="font-sans antialiased text-gray-900 leading-normal tracking-wider bg-cover" style="background-image:url('https://source.unsplash.com/1L71sPT5XKc');">
  <div class="max-w-4xl flex items-center h-auto lg:h-screen flex-wrap mx-auto my-32 lg:my-0">
	<!--Main Col-->
	<div id="profile" class="w-full lg:w-3/5 rounded-lg lg:rounded-l-lg lg:rounded-r-none shadow-2xl bg-white opacity-75 mx-6 lg:mx-0">
		<div class="p-4 md:p-12 text-center lg:text-left">
			<!-- Image for mobile view-->
			<div class="block lg:hidden rounded-full shadow-xl mx-auto -mt-16 h-48 w-48 bg-cover bg-center" style="background-image: url('https://source.unsplash.com/MP0IUfwrn0A')"></div>
            <!--change content based on user's profile_data-->
			<h1 class="text-3xl font-bold pt-8 lg:pt-0">{{ profile.name }}</h1> 
			<div class="mx-auto lg:mx-0 w-4/5 pt-3 border-b-2 border-green-500 opacity-25"></div>
			<p class="pt-4 text-base font-bold flex items-center justify-center lg:justify-start"><svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9v-2zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9v2zm3-8V2H8v1h4z"/></svg>{{ profile.job }}</p>
			<p class="pt-2 text-gray-600 text-xs lg:text-sm flex items-center justify-center lg:justify-start"><svg class="h-4 fill-current text-green-700 pr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm7.75-8a8.01 8.01 0 0 0 0-4h-3.82a28.81 28.81 0 0 1 0 4h3.82zm-.82 2h-3.22a14.44 14.44 0 0 1-.95 3.51A8.03 8.03 0 0 0 16.93 14zm-8.85-2h3.84a24.61 24.61 0 0 0 0-4H8.08a24.61 24.61 0 0 0 0 4zm.25 2c.41 2.4 1.13 4 1.67 4s1.26-1.6 1.67-4H8.33zm-6.08-2h3.82a28.81 28.81 0 0 1 0-4H2.25a8.01 8.01 0 0 0 0 4zm.82 2a8.03 8.03 0 0 0 4.17 3.51c-.42-.96-.74-2.16-.95-3.51H3.07zm13.86-8a8.03 8.03 0 0 0-4.17-3.51c.42.96.74 2.16.95 3.51h3.22zm-8.6 0h3.34c-.41-2.4-1.13-4-1.67-4S8.74 3.6 8.33 6zM3.07 6h3.22c.2-1.35.53-2.55.95-3.51A8.03 8.03 0 0 0 3.07 6z"/></svg> Location - {{ profile.location }}</p>
			<p class="pt-8 text-sm">{{ profile.description }}</p>

			<div class="mt-6 pb-16 lg:pb-0 w-4/5 lg:w-full flex flex-auto mx-auto items-center text-left">
				<a href="{{profile.fb}}/" target="_blank" data-tippy-content="@facebook_handle" class = "p-4"><svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M22.676 0H1.324C.593 0 0 .593 0 1.324v21.352C0 23.408.593 24 1.324 24h11.494v-9.294H9.689v-3.621h3.129V8.41c0-3.099 1.894-4.785 4.659-4.785 1.325 0 2.464.097 2.796.141v3.24h-1.921c-1.5 0-1.792.721-1.792 1.771v2.311h3.584l-.465 3.63H16.56V24h6.115c.733 0 1.325-.592 1.325-1.324V1.324C24 .593 23.408 0 22.676 0"/></svg></a>
				
				<a href="{{profile.tw}}" target="_blank" data-tippy-content="@twitter_handle" class = "p-4"><svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"/></svg></a>
				
				<a href="{{profile.ig}}" target="_blank" data-tippy-content="@instagram_handle" class = "p-4"><svg class="h-6 fill-current text-gray-600 hover:text-green-700" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z"/></svg></a>
			</div>
			{% if current_user.id != profile.id %}
			<form class="flex flex-col" method="POST" action="{{ url_for('profile.ext_profile', id=profile.id) }}"> 
				{{ form.csrf_token }}
				{{ blog_render_field(form.message, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
				
				<button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Send</button>
			</form>
			{% endif %}
		</div>
	</div>
	
	<!--Img Col-->
	<div class="w-full lg:w-2/5">
		<img src="{{profile.img}}" class="rounded-none lg:rounded-lg shadow-2xl hidden lg:block">
	</div>
</div>
</body>
{% endblock %}