BlogApp/views/blog.py
from flask import render_template, request, Blueprint, url_for, redirect, flash
from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename
from BlogApp import db
from BlogApp.forms import *
from BlogApp.models import *
from BlogApp.utilities.plag_checker import *
from BlogApp.utilities.summarizer import *
from BlogApp.utilities.grammar_checker import *
import datetime
from datetime import datetime
from flask_login import login_required, current_user
import readtime
import os
blog = Blueprint('blog', __name__)

def count_likes(blog_id):
    likers = liked_blog.query.filter_by(blog_id=blog_id).all()
    likes = len(likers)
    return likes


def count_dislikes(blog_id):
    dislikers = disliked_blog.query.filter_by(blog_id=blog_id).all()
    dislikes = len(dislikers)
    return dislikes

@blog.route("/display_personal_post/<id>", methods=['GET', 'POST'])  
@login_required  
def display_personal_post(id):
    id = str(id)
    post_data = Profile.query.filter_by(id=current_user.id).first().blogs.filter_by(id=id).first()   
    if post_data is None:
        flash("No blog with that ID belongs to you! Please check your URL and try again!", 'red')
        return redirect(url_for('profile.personal_blogs'))
    else:    
        return render_template('blog/display_personal_post.html', post=post_data)  


@blog.route("/display_post/<id>", methods=['GET', 'POST'])    
@login_required
def display_post(id):
    form = comment_form()
    if request.method == 'POST':
        new = Comment(blog_id=int(id), profile_id=current_user.id, comment=form.comment.data,time = str('Posted on ' + str(datetime.now())))
        post = blog_data.query.filter_by(id=int(id)).first()
        author_message = Message(sender_id=current_user.id,recipient_id=post.author.id,content=(str(current_user.username)+' just commented on your blog "'+str(post.title)+'"'+str(form.comment.data)+'". View profile:'),link=str('/display_post/'+str(post.id)))
        db.session.add(author_message)
        db.session.add(new)
        db.session.commit()
        return redirect(url_for('blog.display_post', id=id) + '#ld')  
        
    id = str(id)
    post_data = blog_data.query.filter_by(id=id).first() 
      
    if post_data: 
        
        next_blog = blog_data.query.filter_by(id=(int(id)+1)).first()  
        prev_blog = blog_data.query.filter_by(id=(int(id)-1)).first()  
        
        post_views = post_data.views
        post_views += 1
        post_data.views = post_views
        db.session.commit()
        
        if post_data.author.id == current_user.id:
            is_owner=True
        else:
            is_owner=False

        is_liked = False
        liked = liked_blog.query.filter_by(blog_id=id).all()
        if liked is not None:
            for i in liked:
                if i.liker_id == current_user.id: 
                    is_liked = True
                    break
    
        is_disliked = False
        disliked = disliked_blog.query.filter_by(blog_id=id).all()
        if disliked is not None:
            for i in disliked:
                if i.disliker_id == current_user.id: 
                    is_disliked = True
                    break
        try:
            disliked = disliked_blog.query.filter_by(blog_id=id).first_or_404()
            is_disliked = True
        except:
            pass
        
        comments = Comment.query.filter_by(blog_id=int(id)).all()
        comments = comments[::-1]
        
        return render_template('blog/display_post.html', post=post_data, next_blog=next_blog, prev_blog=prev_blog, is_owner=is_owner, is_liked=is_liked, is_disliked=is_disliked, comments=comments,  form=form, current_user = current_user,likes = count_likes(id), dislikes = count_dislikes(id))
    else:
        #flash("No blog with that ID! Please check your URL and try again!", 'red')  #this piece of code is being run for no reason idk why
        return redirect(url_for('general.your_blogs'))  


@blog.route("/like_post/<id>", methods=['GET', 'POST']) 
@login_required   
def like_post(id):
    id = str(id)
    liked = Profile.query.filter_by(id=current_user.id).first().liked_blogs
    post = blog_data.query.filter_by(id=id).first()
    to_like = liked_blog(blog_id=id,liker_id=current_user.id)
    db.session.add(to_like)
    try:
        disliked = disliked_blog.query.filter_by(blog_id=id).first_or_404()
        db.session.delete(disliked)
    except:
        pass
    db.session.commit()
    author_message =Message(sender_id=current_user.id,recipient_id=post.author.id,content=(str(current_user.username)+' just liked your post "'+str(post.title)+'". View it here:'),link=str('/display_post/'+str(post.id)))
    db.session.add(author_message)    
    db.session.commit()
    return redirect('/display_post/'+id+'#ld')
    
    
@blog.route("/un_like_post/<id>", methods=['GET', 'POST'])   
@login_required 
def un_like_post(id):
    id = str(id)
    post = blog_data.query.filter_by(id=id).first()
    liked = liked_blog.query.filter_by(blog_id=id).first()
    db.session.delete(liked)
    db.session.commit()
    author_message =Message(sender_id=current_user.id,recipient_id=post.author.id,content=(str(current_user.username)+' just un-liked your blog "'+str(post.title)+'". View it here:'),link=str('/display_post/'+str(post.id)))
    db.session.add(author_message)
    db.session.commit()
    return redirect('/display_post/'+id+"#ld")


@blog.route("/dislike_post/<id>", methods=['GET', 'POST'])  
@login_required  
def dislike_post(id):
    id = str(id)
    post = blog_data.query.filter_by(id=id).first()
    to_dislike = disliked_blog(blog_id=int(id),disliker_id=current_user.id)
    db.session.add(to_dislike)
    try:
        liked = liked_blog.query.filter_by(blog_id=id).first_or_404()
        db.session.delete(liked)
    except:
        pass
    db.session.commit()
    author_message =Message(sender_id=current_user.id,recipient_id=post.author.id,content=(str(current_user.username)+' just disliked your post "'+str(post.title)+'". View it here:'),link=str('/display_post/'+str(post.id)))
    db.session.add(author_message)    
    db.session.commit()
    return redirect('/display_post/'+id+"#ld")


@blog.route("/un_dislike_post/<id>", methods=['GET', 'POST'])    
@login_required
def un_dislike_post(id):
    id = str(id)
    post = blog_data.query.filter_by(id=id).first()
    disliked = disliked_blog.query.filter_by(blog_id=id).first()
    db.session.delete(disliked)
    
    author_message =Message(sender_id=current_user.id,recipient_id=post.author.id,content=(str(current_user.username)+' just un-disliked your blog "'+str(post.title)+'". View it here:'),link=str('/display_post/'+str(post.id)))
    db.session.add(author_message)
    db.session.commit()
    return redirect('/display_post/'+id+"#ld")
        
@blog.route("/plag_check/<id>", methods=['GET', 'POST'])
@login_required
def plag_check(id):
    blog = blog_data.query.filter_by(id=id).first()
    if blog is None:
        flash("No blog with that ID! Please check your URL again!", 'red')
        return redirect(url_for('general.your_blogs'))
    elif blog.author.id != current_user.id:
        flash('You cannot check for plagarism in a post that does not belong to you!', 'red')
        return redirect(url_for('profile.personal_blogs'))    
    else:
        if len(blog.content) >= 100:
            
            if os.path.exists('BlogApp/utilities/test.txt'):
                with open("BlogApp/utilities/test.txt") as f:
                    contents = f.read()
                f.close()
                
                blog_content = blog.content
                for ch in ["\r\n",'\r','\n']:
                        if ch in blog_content:
                            blog_content=blog_content.replace(ch,"")
                
                if (blog_content in contents or contents in blog_content) and (os.path.exists('BlogApp/utilities/train.txt')):
                    plc()
                else:
                    f = open("BlogApp/utilities/test.txt", "w")    
                    f.write(blog_content)
                    f.close()
                    
                    search_query = str(blog.category) + ' ' + str(blog.title)
                    load_dataset(search_query, 10)
                    plc()
            else:
                f = open("BlogApp/utilities/test.txt", "w")    
                f.write(blog.content)
                f.close()
                
                search_query = str(blog.category) + ' ' + str(blog.title)
                load_dataset(search_query, 10)
                plc()
                
            flash('Algorithm success! You can proceed to close the previous window.', 'yellow')
            return redirect(url_for('blog.display_post', id=id))
        else:
            flash('Unable to test dataset as it is too small. Minimum word count: 100 words!', 'yellow')
            return redirect(url_for('blog.display_post', id=id))
    
    
@blog.route("/create_post", methods=['GET', 'POST'])   
@login_required 
def create_post():    
    form = Post()     
    if request.method  == 'POST' and form.validate_on_submit():
        owner = Auth.query.filter_by(id=current_user.id).first().profile
        try:
            synop = generate_summary(correct_text(form.content.data)['result'],1)
        except:
            synop = "Error 404. Something went terribly wrong. Please contact us for assistance. We sincerely apologise for the inconvenience caused!"
        post = blog_data(category=form.category.data, title=form.title.data, content=form.content.data, synopsis=synop, author=owner)
        f = form.img.data
        if f is not None and type(f) != str:
            filename = secure_filename(f.filename)
            records = blog_data.query.all()
            try:
                os.makedirs('BlogApp/static/blogs/'+str(len(records)+1)+'/')
            except:
                pass

BlogApp/templates/blog/create_post.html
{% extends "form_base.html" %} 
{% from "_formhelpers.html" import blog_render_field %} 

{% block title %}Create Post{% endblock %} 

{% block head %}
<style>
    .toggle-path {
        transition: background 0.3s ease-in-out;
    }
    .toggle-circle {
        top: 0.2rem;
        left: 0.25rem;
        transition: all 0.3s ease-in-out;
    }
    #inp:checked ~ .toggle-circle {
        transform: translateX(100%);
    }
    #inp:checked ~ .toggle-path {
        background-color:#81E6D9;
    }
    .body-bg {
        background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
    }

    /* The switch - the box around the slider */
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

    /* Hide default HTML checkbox */
    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
</style>
{% endblock %}

{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Welcome to Unveiled</h3>
        <p class="text-gray-600 pt-2">Upload a post.</p>
    </section>

    <section class="mt-4">
        <form class="flex flex-col" method="POST" action="{{ url_for('blog.create_post') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ blog_render_field(form.img, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.category, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }} 
            {{ blog_render_field(form.title, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.content, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-40") }}
            {{ blog_render_field(form.tags, placeholder="<tag1>, <tag2>, <tag3> etc.", class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}    
            <!-- Rounded switch for grammar checker-->
            <div class='pt-6 text-right text-purple-700 text-m pr-2'>
                <span class='hover:text-purple-900 pr-1'>AI-based Grammar checker: </span>
                <label class="switch">
                    {{ form.grammar_checker() }}
                    <span class="slider round"></span>
                </label>
            </div>
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Upload</button>
        </form>
    </section>
</main>
{% endblock %} 

<!--
{% block script %}
<script type="text/javascript">
    window.addEventListener('beforeunload', function (e) {
        e.preventDefault();
        e.returnValue = '';
    });
</script>
{% endblock %}
-->

{% block href1 %}/your_blogs{% endblock %}       {% block href_tag1 %}Blogs{% endblock %}
{% block href2 %}/dashboard{% endblock %}       {% block href_tag2 %}Dashboard{% endblock %}

BlogApp/templates/blog/display_personal_post.html
{% extends "base.html" %} 
{% from "_formhelpers.html" import blog_render_field %} 

{% block title %} {{ post['title'] }} {% endblock %} 

{% block body %}
<body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <!--Progress Bar-->
    <div id="progress" class="fixed w-full z-10 top-0 h-1 z-20 top-0" style="background:linear-gradient(to right, #4dc0b5 var(--scroll), transparent 0);"></div>
    <!--Container-->
    <div class="container w-full md:max-w-3xl mx-auto pt-20">

        <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family:Georgia,serif;">

            <!--Title-->
            <div class="font-sans">
                <p class="text-base md:text-sm text-green-500 font-bold text-left">&lt; <a href="/personal_blogs" class="text-base md:text-sm text-green-500 font-bold no-underline hover:underline">BACK TO YOUR BLOGS</a></p>
                <h1 class="font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl">{{ post.title }}</h1>
                <p class="text-sm md:text-base font-normal text-gray-600">Published on {{ post.date_created.strftime("%B %d, %Y at %H:%M %p") }}</p>
            </div>
            <!--all content are jinja values which are determined by the post that is being called-->

            <!--Content-->
            <p class="py-6 whitespace-pre-wrap">{{ post.content }}</p>
        </div>

        <!--Category -->
        <div class="text-base md:text-sm text-gray-500 px-4 py-6">
            Tags: 
            {% for tag in post.tags %}
                {% if loop.index != loop.length %}
                {{tag.name}}, 
                {% else %}
                {{tag.name}}
                {% endif %}
            {% endfor %}
        </div>

        <!--Divider-->
        <hr class="border-b-2 border-gray-400 mb-6 mx-4">

        <!--Author-->
        <div class="flex w-full items-center font-sans px-4 py-6">
            <img class="w-10 h-10 rounded-full mr-4" src="http://i.pravatar.cc/300" alt="Avatar of Author">
            <!--random avatar for everyone-->
            <div class="flex-1 px-2">
                <p class="text-base font-bold text-base md:text-xl leading-none mb-2">{{ post.author.name }}</p>
                <p class="text-gray-600 text-xs md:text-base">Minimalist blog by a beginner writer</p>
            </div>
            <div class="justify-end">
                <button onclick="window.location.href='/dashboard'" class="bg-transparent border border-gray-500 hover:border-green-500 text-xs text-gray-500 hover:text-green-500 font-bold py-2 px-4 rounded-full">Read More</button>
            </div>
            <!--change after linking tables-->
        </div>

        <!--edit post button-->
        <p class="text-base md:text-sm text-green-500 font-bold mb-6 text-right"><a href="/edit_post/{{ post.id }}" class="text-base md:text-sm text-green-500 font-bold no-underline hover:underline">EDIT THIS POST</a> &gt;</p>
        <!--plagarism checker button-->
        <p class="text-base md:text-sm text-green-500 font-bold mb-6 text-right"><a target='_blank' href="/plag_check/{{ post.id }}" class="text-base md:text-sm text-green-500 font-bold no-underline hover:underline">DETECT PLAGARSIM</a> &gt;</p>
        <!--generate grammar checker dataframe button-->
        <p class="text-base md:text-sm text-green-500 font-bold mb-6 text-right"><a target='_blank' href="/gc_df/{{ post.id }}" class="text-base md:text-sm text-green-500 font-bold no-underline hover:underline">CORRECT GRAMMAR</a> &gt;</p>

        <!--Divider-->
        <hr class="border-b-2 border-gray-400 mb-6 mx-4">

    </div>

    <!--Js-->
    <script>
        /* Progress bar */
        //Source: https://alligator.io/js/progress-bar-javascript-css-variables/
        var h = document.documentElement,
            b = document.body,
            st = 'scrollTop',
            sh = 'scrollHeight',
            progress = document.querySelector('#progress'),
            scroll;
        var scrollpos = window.scrollY;
        var header = document.getElementById("header");
        var navcontent = document.getElementById("nav-content");

        document.addEventListener('scroll', function() {

            /*Refresh scroll % width*/
            scroll = (h[st] || b[st]) / ((h[sh] || b[sh]) - h.clientHeight) * 100;
            progress.style.setProperty('--scroll', scroll + '%');

            /*Apply classes for slide in bar*/
            scrollpos = window.scrollY;
        });
    </script>
</body>
{% endblock %}

BlogApp/templates/blog/edit_comment.html
{% extends "form_base.html" %}
{% from "_formhelpers.html" import blog_render_field %}

{% block title %} Edit your Comment {% endblock %}
    
{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Edit your comment</h3>
    </section>

    <section class="mt-4">
        <form class="flex flex-col" method="POST" action="/edit_comment/{{id}}"> 
            {{ form.csrf_token }}
            {{ blog_render_field(form.new, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }} 
            <input type = 'hidden' value = '{{prev}}' name = 'prev'></input>
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Update</button>
        </form>
    </section>
</main>
{% endblock %}

{% block href1 %}/your_comments{% endblock %}       {% block href_tag1 %}Your Comments{% endblock %}
{% block href2 %}/contact_us{% endblock %}          {% block href_tag2 %}Contact Us{% endblock %}

    

BlogApp/templates/blog/edit_post.html
{% extends "form_base.html" %}
{% from "_formhelpers.html" import blog_render_field %}

{% block title %}Edit "{{ post_data.title }}"{% endblock %}
    
{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Welcome to Unveiled</h3>
        <p class="text-gray-600 pt-2">Edit "{{ post_data.title }}".</p>
    </section>

    <section class="mt-4">
        <form class="flex flex-col" method="POST" action="{{ url_for('blog.edit_post', id=post_data.id) }}" enctype="multipart/form-data"> 
            {{ form.csrf_token }}
            {{ blog_render_field(form.img, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.category, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }} 
            {{ blog_render_field(form.title, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.content, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-40") }}
            {{ blog_render_field(form.tags, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Upload</button>
        </form>
        <div class="flex justify-end"> 
            <form action="{{ url_for('blog.delete_post', id=post_data.id) }}" method='POST'>   <!--form imput to delete the post, sends over the id that it received from the edit_post route to the delete_post route-->
                <input type='submit' value='Delete this post -->' onclick="return confirm('Are you sure you want to delete this post?')" class="text-base bg-transparent mt-4 mb-0 text-purple-900 hover:text-purple-700 hover:underline mb-6">
                                                                    <!--conformation message-->
            </form>
        </div>
    </section>
</main>
{% endblock %}

{% block script %}
<script type="text/javascript">
    window.addEventListener('beforeunload', function (e) {
        e.preventDefault();
        e.returnValue = '';
    });
</script>
{% endblock %}

{% block href1 %}/display_post/{{post_data.id}}{% endblock %}       {% block href_tag1 %}Back{% endblock %}
{% block href2 %}/contact_us{% endblock %}                          {% block href_tag2 %}Contact Us{% endblock %}

    

BlogApp/templates/blog/gc_df_template.html
{% extends "base.html" %}
{% block title %} Output {% endblock %}

{% block head %}
<style>
.mystyle {
    font-size: 12pt; 
    font-family: Arial;
    border-collapse: collapse; 
    border: 3px solid silver;
}

body{
    margin: 50px;
    color: black;
}

th{
    text-transform: uppercase; 
    text-align: center;
}

.mystyle td, th {
    padding: 8px;
}

.mystyle tr:nth-child(even) {
    background: #E0E0E0;
}

/*
.mystyle tr:hover {
    background: silver;
    cursor: pointer;
}*/
</style>
{% endblock %}


{% block body %} 
<section class="text-gray-600 body-font">
    <div class="container py-12 mx-auto">
        <div class="flex flex-col text-center w-full mb-10">
            <h2 class="text-xs text-yellow-500 tracking-widest font-medium title-font mb-1">Output</h2>
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Compiled Dataframe of Errors:</h1>
            <p>{{ table|safe }}</p>
        </div>
    </div>
</section>

<button onclick="window.location.href='/display_post/{{ item.id }}'" class="w-full h-12 px-12 text-white transition-colors duration-150 bg-indigo-600 rounded-lg focus:shadow-outline hover:bg-indigo-800">----- Back to the post -----</button>
{% endblock %}