BlogApp/views/general.py
import json, os
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from BlogApp.utilities.calculate import calculate, Time
#from BlogApp.forms import study1#, study2
from BlogApp.forms import *
from BlogApp.models import *
from BlogApp import cache
#from BlogApp import gpt_125M, gpt_13B, gpt_27B
from BlogApp.utilities.essay_starter import *
from BlogApp.utilities.plag_checker import *
import readtime

def count_likes(blog_id):
    likers = liked_blog.query.filter_by(blog_id=blog_id).all()
    likes = len(likers)
    return likes

general = Blueprint('general', __name__)

global newsletter_subs   
newsletter_subs = []

@general.route("/", methods=['GET','POST'])
#@cache.cached(timeout=50)          #uncomment in final version
def root():
    return render_template('general/home.html')  


@general.route("/our_journey", methods=['GET','POST'])
#@cache.cached(timeout=50)          #uncomment in final version
def our_journey():
    readers = Profile.query.count()
    blogs = blog_data.query.count()
    writers = 0
    for i in Profile.query.all():
        if i.blogs.count() != 0:
            writers+=1
    return render_template('general/our_journey.html', readers=readers, blogs=blogs, writers=writers)  
 
 
@general.route("/tbfy", methods=['GET','POST'])
#@cache.cached(timeout=300)          #uncomment in final version
def tbfy():
    return render_template('general/tbfy.html')    


@general.route("/ssr", methods=['GET','POST'])    #ssr --> show subscription results
def ssr():
    newsletter_subs.append(request.form['entry'])
    if current_user.is_authenticated:
        return render_template('general/ssr.html', form=newsletter_subs)    
    else:
        return redirect(url_for('general.about_us'))
  

@general.route("/about_us", methods=['GET','POST'])  
#@cache.cached(timeout=50)   
def about_us():
    return render_template('general/about_us.html')
  
@general.route("/featured_blogs", methods=['GET', 'POST']) 
@general.route("/featured_blogs/<int:limit>", methods=['GET', 'POST'])  
def featured_blogs(limit=5): 
    records = blog_data.query.order_by(blog_data.views.desc()).limit(limit).all()
    return render_template('general/featured_blogs.html', posts=records, reading_time=reading_time, count_likes=count_likes)


def reading_time(text): 
    return readtime.of_text(str(text)).text

ROWS_PER_PAGE=2
@general.route("/your_blogs", methods=['GET', 'POST'])  
def your_blogs(): 
    tags = Tag.query.with_entities(Tag.name).order_by(Tag.name).group_by(Tag.name).all()
    page = request.args.get('page', 1, type=int)
    records = blog_data.query.order_by(blog_data.category).paginate(page=page, per_page=ROWS_PER_PAGE)
    print(records.items)
    all_blogs = blog_data.query.order_by(blog_data.category).all()
    return render_template('general/your_blogs.html', title='Minimal Blogs', posts=records, tags=tags,reading_time=reading_time, count_likes=count_likes, all_blogs = all_blogs)  


@general.route('/topic/<tag>')
@login_required
def topic(tag):
    try:
        topic = Tag.query.filter_by(name=tag).first()
    except:
        flash('Topic not found!','yellow')
        return redirect(url_for('general.your_blogs'))
    page = request.args.get('page', 1, type=int)
    records = topic.blogs.order_by(blog_data.category).paginate(page=page, per_page=ROWS_PER_PAGE)
    return render_template('general/your_blogs.html', title="#"+tag, posts=records,reading_time=reading_time, count_likes=count_likes) 


@general.route("/contact_us", methods=['GET','POST'])  
#@cache.cached(timeout=50)  
def contact_us():
    return render_template('general/contact_us.html')

@general.route("/scr", methods=['GET','POST'])    #scr --> show contact results
def scr():
    if os.path.exists("contact_data.json"):    
        with open("contact_data.json") as datafile:
            saveddata = json.load(datafile)
    else:
        saveddata = {}

    if request.method == "POST":
        saveddata[request.form['email']] = request.form

    with open("BlogApp/contact_data.json", "w") as datafile: 
        json.dump(saveddata, datafile)

    if current_user.is_authenticated:
        return render_template('general/scr.html', form=saveddata)    
    else:
        return redirect(url_for('general.about_us'))
        

@general.route("/essay_starter", methods=['GET','POST'])    
def essay_start():
    form = essay_starter(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        data = generate(form.title.data, form.length.data, form.generator.data, form.temperature.data)
        data += '...'
        flash('You can proceed to close the previous window.', 'yellow')
        return render_template('general/essay_starter_results.html', output=data)
    
    flash('A larger model and a longer text length will result in an exponentially longer waiting time!', 'yellow')
    return render_template('general/essay_starter_form.html', form=form)

@general.route("/plag_check_form", methods=['GET','POST'])    
def plag_check():
    form = plag_check_form(num_res=10)
    if request.method == 'POST' and form.validate_on_submit():
        f = open("BlogApp/utilities/test.txt", "w")    
        f.write(form.content.data)
        f.close()
        
        load_dataset(form.query.data, form.num_res.data)
        plc()
        flash('Algorithm success! You can proceed to close the previous window.', 'yellow')
        return redirect(url_for('general.your_blogs'))
    
    return render_template('general/plag_check_form.html', form=form)
            

        
@general.errorhandler(404)    #404 errorhandler
@cache.cached(timeout=300) 
def not_found(error):
  return render_template("404.html") 


@general.route('/writers')
def writers():
    users = Profile.query.all()
    return render_template('/general/users.html',users=users)




  

BlogApp/templates/_formhelpers.html
{% macro blog_render_field(field) %}

  <div class="mt-6 pt-3 rounded bg-gray-200">
    {{ field.label(class_="block text-gray-700 text-sm font-bold mb-2 ml-3") }}
    {{ field(**kwargs)|safe }}
  </div>

  <div class='bg-white mt-0'>
    {% if field.errors %}
      {% for error in field.errors %}
        <li class='text-red-600 my-1 bg-white text-sm'>{{ error }}</li>
      {% endfor %}
    {% endif %}
  </div>

  </dd>
{% endmacro %}

BlogApp/templates/base.html
<!DOCTYPE html>
<html lang='en-sg'>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Pranav Tumminkatti and Joshua Sin">
	<meta name="description" content="A blogsite">
	<meta name="robots" content="all">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <!--JQuery-->
  <script src="jquery-3.5.1.min.js"></script>
  <!-- Font Awesome -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
  
  <title>{% block title %} Default title {% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
    {% block header %}
    <style>

/* Links inside the navbar */
.navbar a {
  float: left;
  font-size: 16px;
  text-align: center;
  text-decoration: none;
}

/* The dropdown container */
.dropdown {
  float: left;
  overflow: hidden;
}

/* Dropdown button */
.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  background-color: inherit;
  font-family: inherit; /* Important for vertical align on mobile phones */
  margin: 0; /* Important for vertical align on mobile phones */
}

/* Dropdown content (hidden by default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

/* Add a grey background color to dropdown links on hover */
.dropdown-content a:hover {
  background-color: #ddd;
}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
  display: block;
}
    </style>
    <!--Header-->
    <header class="text-gray-600 body-font">
        <div class="container mx-auto flex flex-wrap p-3 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <img src="{{url_for('static', filename='Unveiled.jpg')}}" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"/>
            <span class="ml-3 text-xl">dAIgnosis</span>
          </a>
          <nav class="navbar md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
            <a href='/' class="mr-5 hover:text-gray-900">Home</a>
            <a href='/clinics' class="mr-5 hover:text-gray-900">clinics</a>
            {% if current_user.is_authenticated %}  <!--show in navbar only if user is logged in-->
              <a href='/diagnosis' class="mr-5 hover:text-gray-900">Diagnosis</a>
              <a href='/find_clinic' class="mr-5 hover:text-gray-900">Book doctors near you</a>
              <a href='/healthmap' class="mr-5 hover:text-gray-900">Healthmap</a>
            {% endif %} 
          </nav>

          {% if current_user.is_authenticated %}  <!--in the box at the top-right of the page, display Login/Sign Up if the user is not logged in, and Your Profile if he is-->
          <button onclick="window.location.href='/dashboard'" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">{{ current_user.profile.name|capitalize }}
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
          {% else %}
          <button onclick="window.location.href='/login'" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login / Sign up
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </button>
          {% endif %}
        </div>
      </header>
      {% endblock %}
      
      <!--Error Messages-->
      {% block warning %}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          <ul>
          {% for category, message in messages %}
            <li>
              <div class="text-white px-6 py-4 border-0 rounded relative mx-24 mb-0 bg-{{ category }}-700 my-3 z-50">
                <span class="text-xl inline-block mr-5 align-middle">
                  <i class="fas fa-bell"></i>
                </span>
                <span class="inline-block align-middle mr-8">
                  <b class="capitalize">Message:</b> {{ message }}
                </span>
                <button id='flash-x' class="absolute bg-{{ category }}-700 text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none" onclick="closeAlert(event)">
                  <span>×</span>
                </button>
              </div>
            </li>
          {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
      {% endblock %}

      {% block body %}{% endblock %}

        {% block footer %}
        <!--Footer-->
        <footer class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-wrap md:text-left text-center order-first">

            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">LOCATION</h2>
                <nav class="list-none mb-10">
                    <a href='https://www.google.com.sg/maps/place/Raffles+Institution/@1.3466753,103.8412342,17z/data=!3m1!4b1!4m5!3m4!1s0x31da173fcd2fd3c7:0x8216edf9d591f42e!8m2!3d1.3466753!4d103.8434229' target="_blank" class="text-gray-600 hover:text-gray-800">1 Raffles Institution Lane, Singapore 575954</a>
                </nav>
            </div>

            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CONTACT</h2>
                <nav class="list-none mb-10">
                    <p class="text-gray-600 hover:text-gray-800">(+65) 6419 9242</p>
                    <p class="text-gray-600 hover:text-gray-800">24ypran395i@student.ri.edu.sg</p>
                </nav>
            </div>

            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
                <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">FOLLOW</h2>
                <nav class="list-none mb-10">
                <li>
                    <a href='https://www.instagram.com'target="_blank" class="text-gray-600 hover:text-gray-800">Instagram</a>
                </li>
                <li>
                    <a href='https://www.facebook.com' target="_blank" class="text-gray-600 hover:text-gray-800">Facebook</a>
                </li>
                <li>
                    <a href='https://twitter.com' target="_blank" class="text-gray-600 hover:text-gray-800">Twitter</a>
                </li>
                </nav>
            </div>

            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">SUBSCRIBE</h2>
              <div class="flex xl:flex-nowrap md:flex-nowrap lg:flex-wrap flex-wrap justify-center items-end md:justify-start">
                
                <form action="{{ url_for('general.ssr') }}" method="POST">
                  <div class="relative w-40 sm:w-auto xl:mr-4 lg:mr-0 sm:mr-4 mr-2 mb-2.5">
                    <label for="entry" class="leading-7 text-sm text-gray-600">Subscribe to our daily newsletter!</label>
                    <input type="email" id="email" name="entry" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:bg-transparent focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                  </div>
                  <button class="lg:mt-2 xl:mt-0 flex-shrink-0 inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Submit</button>
                </form>

              </div>
            </div>

          </div>
        </div>
        <div class="bg-gray-100">
            <div class="container px-5 py-6 mx-auto flex items-center sm:flex-row flex-col">
            <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                </svg>
                <span class="ml-3 text-xl">Unveiled</span>
            </a>
            <p class="text-sm text-gray-500 sm:ml-6 sm:mt-0 mt-4">© 2021 Unveiled — @pranavtumminkatti, @joshuasin</p>
            </div>
        </div>
        </footer>
        {% endblock %}

        
        <script>
          function closeAlert(event){
            let element = event.target;
            while(element.nodeName !== "BUTTON"){
              element = element.parentNode;
            }
            element.parentNode.parentNode.removeChild(element.parentNode);
          }
        </script>
        {% block script %}{% endblock %}
</body>
</html>

BlogApp/templates/form_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Pranav Tumminkatti">
	<meta name="description" content="A blogsite">
	<meta name="robots" content="all">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <style>
        .body-bg {
            background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
        }
    </style>
    {% block head %} {% endblock %}
</head>

<body class="body-bg min-h-screen pt-6 md:pt-8 pb-6 px-1 md:px-0" style="font-family:'Lato',sans-serif;">
    {% block warning %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
            {% for category, message in messages %}
            <li>
                <div class="text-white px-6 py-4 border-0 rounded relative mt-0 mx-20 bg-{{ category }}-700 mb-8">
                <span class="text-xl inline-block mr-5 align-middle">
                    <i class="fas fa-bell"></i>
                </span>
                <span class="inline-block align-middle mr-8">
                    <b class="capitalize">Message:</b> {{ message }}
                </span>
                <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 top-0 mt-4 mr-6 outline-none focus:outline-none" onclick="closeAlert(event)">
                    <span>×</span>
                </button>
                </div>
            </li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    {% endblock %}

    {% block header %}
    <header class="max-w-lg mx-auto mt-0">
        <h1 class="text-4xl font-bold text-white text-center">Unveiled</h1>
    </header>
    {% endblock %}

    {% block main %} {% endblock %}
    
    {% block footer %}
    <footer class="max-w-lg mx-auto flex justify-center text-white">
        <a href="{% block href1 %}/{% endblock %}" class="hover:underline">{% block href_tag1 %}{% endblock %}</a>
        <span class="mx-3">•</span>
        <a href="{% block href2 %}/{% endblock %}" class="hover:underline">{% block href_tag2 %}{% endblock %}</a>
    </footer>
    {% endblock %}

    
    <script>
        function closeAlert(event){
        let element = event.target;
        while(element.nodeName !== "BUTTON"){
            element = element.parentNode;
        }
        element.parentNode.parentNode.removeChild(element.parentNode);
        }
    </script>
    {% block script %}{% endblock %}
</body>
</html>

BlogApp/templates/schedulebase.html
<!DOCTYPE html>
<html lang='en-sg'>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Joshua Sin">
	<meta name="description" content="A blogsite">
	<meta name="robots" content="all">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Font Awesome -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
  <title>{% block title %} Scheduler app {% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
  <div class = 'container'>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a href = '/studytools' class="nav-link active">Home</a>
      <a href = '/studytools/scheduler' class="nav-link active">New Schedule</a>
      <a href = '/' class="nav-link active">Unveiled Home</a>
      <a href = '/dashboard' class="nav-link active">Your Profile</a>
    </nav>
    {% block body %}
    {% endblock %}
  </div>
</body>