BlogApp/views/general.py
import json, os
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from BlogApp.utilities.calculate import calculate, Time
#from BlogApp.forms import study1#, study2
from BlogApp.forms import *
from BlogApp.models import *
from BlogApp import cache
#from BlogApp import gpt_125M, gpt_13B, gpt_27B
from BlogApp.utilities.essay_starter import *
from BlogApp.utilities.plag_checker import *
import readtime

def count_likes(blog_id):
    likers = liked_blog.query.filter_by(blog_id=blog_id).all()
    likes = len(likers)
    return likes

general = Blueprint('general', __name__)

global newsletter_subs   
newsletter_subs = []

@general.route("/", methods=['GET','POST'])
#@cache.cached(timeout=50)          #uncomment in final version
def root():
    return render_template('general/home.html')  


@general.route("/our_journey", methods=['GET','POST'])
#@cache.cached(timeout=50)          #uncomment in final version
def our_journey():
    readers = Profile.query.count()
    blogs = blog_data.query.count()
    writers = 0
    for i in Profile.query.all():
        if i.blogs.count() != 0:
            writers+=1
    return render_template('general/our_journey.html', readers=readers, blogs=blogs, writers=writers)  
 
 
@general.route("/tbfy", methods=['GET','POST'])
#@cache.cached(timeout=300)          #uncomment in final version
def tbfy():
    return render_template('general/tbfy.html')    


@general.route("/ssr", methods=['GET','POST'])    #ssr --> show subscription results
def ssr():
    newsletter_subs.append(request.form['entry'])
    if current_user.is_authenticated:
        return render_template('general/ssr.html', form=newsletter_subs)    
    else:
        return redirect(url_for('general.about_us'))
  

@general.route("/about_us", methods=['GET','POST'])  
#@cache.cached(timeout=50)   
def about_us():
    return render_template('general/about_us.html')
  
@general.route("/featured_blogs", methods=['GET', 'POST']) 
@general.route("/featured_blogs/<int:limit>", methods=['GET', 'POST'])  
def featured_blogs(limit=5): 
    records = blog_data.query.order_by(blog_data.views.desc()).limit(limit).all()
    return render_template('general/featured_blogs.html', posts=records, reading_time=reading_time, count_likes=count_likes)


def reading_time(text): 
    return readtime.of_text(str(text)).text

ROWS_PER_PAGE=2
@general.route("/your_blogs", methods=['GET', 'POST'])  
def your_blogs(): 
    tags = Tag.query.with_entities(Tag.name).order_by(Tag.name).group_by(Tag.name).all()
    page = request.args.get('page', 1, type=int)
    records = blog_data.query.order_by(blog_data.category).paginate(page=page, per_page=ROWS_PER_PAGE)
    print(records.items)
    all_blogs = blog_data.query.order_by(blog_data.category).all()
    return render_template('general/your_blogs.html', title='Minimal Blogs', posts=records, tags=tags,reading_time=reading_time, count_likes=count_likes, all_blogs = all_blogs)  


@general.route('/topic/<tag>')
@login_required
def topic(tag):
    try:
        topic = Tag.query.filter_by(name=tag).first()
    except:
        flash('Topic not found!','yellow')
        return redirect(url_for('general.your_blogs'))
    page = request.args.get('page', 1, type=int)
    records = topic.blogs.order_by(blog_data.category).paginate(page=page, per_page=ROWS_PER_PAGE)
    return render_template('general/your_blogs.html', title="#"+tag, posts=records,reading_time=reading_time, count_likes=count_likes) 


@general.route("/contact_us", methods=['GET','POST'])  
#@cache.cached(timeout=50)  
def contact_us():
    return render_template('general/contact_us.html')

@general.route("/scr", methods=['GET','POST'])    #scr --> show contact results
def scr():
    if os.path.exists("contact_data.json"):    
        with open("contact_data.json") as datafile:
            saveddata = json.load(datafile)
    else:
        saveddata = {}

    if request.method == "POST":
        saveddata[request.form['email']] = request.form

    with open("BlogApp/contact_data.json", "w") as datafile: 
        json.dump(saveddata, datafile)

    if current_user.is_authenticated:
        return render_template('general/scr.html', form=saveddata)    
    else:
        return redirect(url_for('general.about_us'))
        

@general.route("/essay_starter", methods=['GET','POST'])    
def essay_start():
    form = essay_starter(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        data = generate(form.title.data, form.length.data, form.generator.data, form.temperature.data)
        data += '...'
        flash('You can proceed to close the previous window.', 'yellow')
        return render_template('general/essay_starter_results.html', output=data)
    
    flash('A larger model and a longer text length will result in an exponentially longer waiting time!', 'yellow')
    return render_template('general/essay_starter_form.html', form=form)

@general.route("/plag_check_form", methods=['GET','POST'])    
def plag_check():
    form = plag_check_form(num_res=10)
    if request.method == 'POST' and form.validate_on_submit():
        f = open("BlogApp/utilities/test.txt", "w")    
        f.write(form.content.data)
        f.close()
        
        load_dataset(form.query.data, form.num_res.data)
        plc()
        flash('Algorithm success! You can proceed to close the previous window.', 'yellow')
        return redirect(url_for('general.your_blogs'))
    
    return render_template('general/plag_check_form.html', form=form)
            

        
@general.errorhandler(404)    #404 errorhandler
@cache.cached(timeout=300) 
def not_found(error):
  return render_template("404.html") 


@general.route('/writers')
def writers():
    users = Profile.query.all()
    return render_template('/general/users.html',users=users)




  

BlogApp/templates/general/about_us.html
{% extends "base.html" %}
{% block title %} About Us {% endblock %}
{% block body %} 
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-col">
      <div class="lg:w-4/6 mx-auto">
        <div class="rounded-lg h-64 overflow-hidden">
          <img alt="content" class="object-cover object-center h-full w-full" src="https://source.unsplash.com/1200x500/?blog,writing">
        </div>
        <div class="flex flex-col sm:flex-row mt-10">
          <div class="sm:w-1/3 text-center sm:pr-8 sm:py-8">
            <div class="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
            <div class="flex flex-col items-center text-center justify-center">
              <h2 class="font-medium title-font mt-4 text-gray-900 text-lg">Michael Scofield</h2>
              <div class="w-12 h-1 bg-green-500 rounded mt-2 mb-4"></div>
              <p class="text-base">Unveiled is a great blogsite that I use to post all of my blogs posts!</p>
            </div>
          </div>
          <div class="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l border-gray-200 sm:border-t-0 border-t mt-4 pt-4 sm:mt-0 text-center sm:text-left">
            <p class="leading-relaxed text-lg mb-4">Unveiled is a great place for everybody to start writing. It provides a large reader base for all your content and the sophisticated Unveiled algorithm will ensure that your content reaches all of Unveiled's audience. Unveiled gives you the freedom to express your hearts desire in a safe space of kind and respectful readers. Rest assured, you will have an amazing time writing at Unveiled Singapore.</p>
            <a href='/create_post' class="text-green-500 inline-flex items-center">Start writing today 
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="text-gray-600 body-font">
    <div class="container px-5 py-16 pt-10 mx-auto">
      <div class="flex flex-wrap lg:w-4/5 sm:mx-auto sm:mb-2 -mx-2">
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Safe and easy</span>
          </div>
        </div>
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Large community of users</span>
          </div>
        </div>
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Huge audience and reader base</span>
          </div>
        </div>
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Free plagarism checking software for your posts</span>
          </div>
        </div>
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Like and dislike functions for blogs</span>
          </div>
        </div>
        <div class="p-2 sm:w-1/2 w-full">
          <div class="bg-gray-100 rounded flex p-4 h-full items-center">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" class="text-yellow-500 w-6 h-6 flex-shrink-0 mr-4" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
            <span class="title-font font-medium">Scheduler to keep track of your time</span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-4">
        <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="http://i.pravatar.cc/302">
            <p class="leading-relaxed">We have come a long way since we started developing this app and we hope that our users enjoy using this app</p>
            <span class="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">PRANAV TUMMINKATTI</h2>
            <p class="text-gray-500">Founder of Unveiled</p>
          </div>
        </div>
        <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="http://i.pravatar.cc/300">
            <p class="leading-relaxed">Unveiled is the perfect place for anybody who is new to blogging and also for professional bloggers. I started writing with Unveiled when I was just starting off my blogging career. Today, I enjoy sharing my content with all of my fellow readers. Thank you Unveiled!</p>
            <span class="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">LINCON J WILLIAMS</h2>
            <p class="text-gray-500">Fellow Writer</p>
          </div>
        </div>
        <div class="lg:w-1/3 lg:mb-0 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="http://i.pravatar.cc/305">
            <p class="leading-relaxed">A lot of time and effort was put into developing this app for the students of Singapore. Please do submit feedback for the app in the contact_us page! Thanks!</p>
            <span class="inline-block h-1 w-10 rounded bg-blue-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">JOSHUA SIN</h2>
            <p class="text-gray-500">Co-Founder of Unveiled</p>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

BlogApp/templates/general/contact_us.html
{% extends "base.html" %}
{% block title %} Contact Us {% endblock %}
{% block body %} 
<section class="text-gray-600 body-font relative">
    <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
      <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
        <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=%C4%B0zmir+(My%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed" style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe>
        <div class="bg-white relative flex flex-wrap py-6 rounded shadow-md">
          <div class="lg:w-1/2 px-6">
            <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">ADDRESS</h2>
            <p class="mt-1">1 Raffles Institution Ln, Singapore 575954</p>
          </div>
          <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">
            <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">EMAIL</h2>
            <a class="text-indigo-500 leading-relaxed">24ypran395i@student.ri.edu.sg</a>
            <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs mt-4">PHONE</h2>
            <p class="leading-relaxed">+65 6419 9242</p>
          </div>
        </div>
      </div>
      <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
        <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Feedback</h2>
        <p class="leading-relaxed mb-5 text-gray-600">Please give us feedback on our new blogsite.</p>
        <form action="{{ url_for('general.scr') }}" method="POST"> 
            <div class="relative mb-4">
                <label for="name" class="leading-7 text-sm text-gray-600">Name</label>
                <input type="text" id="name" name="name" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
            
                <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
                <input type="email" id="email" name="email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                
                <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
                <textarea id="message" name="message" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
            </div>
            <button class="text-white w-full bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
        </form>
        <p class="text-xs text-gray-500 mt-3">Thank you for your response</p>
      </div>
    </div>
  </section>
{% endblock %}

BlogApp/templates/general/essay_starter_form.html
{% extends "form_base.html" %} 
{% from "_formhelpers.html" import blog_render_field %} 

{% block title %} Essay starter {% endblock %} 

{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Essay starter program</h3>
        <p class="text-gray-600 pt-2">Use this to help start your essays!</p>
    </section>

    <section class="mt-4">
        <form class="flex flex-col" method="POST" target='_blank' action="{{ url_for('general.essay_start') }}" onsubmit="showHide();">
            {{ form.csrf_token }}
            {{ blog_render_field(form.generator, class="bg-gray-200 w-full text-gray-900 border-b-4 border-gray-300 px-0 py-2 pb-5") }}
            {{ blog_render_field(form.title, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.length, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.temperature, placeholder='Integer between 0 and 1', class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Generate</button>
        </form>
        <!--only works with chrome-->
        <a class="text-sm text-right flex justify-end text-purple-600 hover:text-purple-800 hover:underline mt-6 mb-2" id='hidden_div' style="display:none" href="javascript:window.open('','_self').close();">Close Tab --></a>
    </section>
</main>
{% endblock %} 


{% block script %}
<script type="text/javascript">
    function showHide() {
      var div = document.getElementById("hidden_div");
      if (div.style.display == 'none') {
        div.style.display = '';
      }
      else {
        div.style.display = 'none';
      }
    }
</script>
{% endblock %}


{% block href1 %}/{% endblock %}                          {% block href_tag1 %}Home{% endblock %}
{% block href2 %}/contact_us{% endblock %}                {% block href_tag2 %}Contact Us{% endblock %}

BlogApp/templates/general/essay_starter_results.html
{% extends "base.html" %}
{% block title %} Output {% endblock %}

{% block body %} 
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-yellow-500 tracking-widest font-medium title-font mb-1">Output</h2>
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Your Paragraph:</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">{{output|capitalize}}</p>
    </div>
</section>
{% endblock %}

BlogApp/templates/general/plag_check_form.html
{% extends "form_base.html" %} 
{% from "_formhelpers.html" import blog_render_field %} 

{% block title %} Plagarism Checker {% endblock %} 

{% block main %}
<main class="bg-white max-w-lg mx-auto p-6 md:p-12 my-8 rounded-lg shadow-2xl">
    <section>
        <h3 class="font-bold text-2xl">Plagarism Checker</h3>
        <p class="text-gray-600 pt-2">Use this feature to detect plagarism in your essays!</p>
    </section>

    <section class="mt-0">
        <form class="flex flex-col" method="POST" target='_blank' action="{{ url_for('general.plag_check') }}">
            {{ form.csrf_token }}
            {{ blog_render_field(form.query, class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            {{ blog_render_field(form.content, placeholder='Minimum 100 characters', class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-40") }}
            {{ blog_render_field(form.num_res, placeholder='Number of websites to scrape', class="bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3") }}
            <button class="bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 rounded shadow-lg hover:shadow-xl transition duration-200 mt-6" type="submit">Get Results</button>
        </form>
    </section>
</main>
{% endblock %} 


{% block href1 %}/your_blogs{% endblock %}                {% block href_tag1 %}Blogs{% endblock %}
{% block href2 %}/contact_us{% endblock %}                {% block href_tag2 %}Contact Us{% endblock %}

BlogApp/templates/general/scr.html
{% extends "base.html" %}
{% block title %} Contact Form Results {% endblock %}
{% block body %} 
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-center mx-auto">
        {% if not form %}
        <p class="flex-grow sm:pr-16 text-xl font-medium title-font text-gray-800">No data available yet!</p>
        {% else %}
        <table class='relative w-full border overflow-auto mr-8'>
            <caption>Contact us form data-entry table</caption>
            <tr>
                <th class="top-0 px-6 py-3 text-red-900 bg-red-300">Name</th>
                <th class="top-0 px-6 py-3 text-red-900 bg-red-300">Email</th>
                <th class="top-0 px-6 py-3 text-red-900 bg-red-300">Message</th>
            </tr>
            {% for email in form %}
                <tr class="divide-y bg-red-100 hover:bg-red-200">
                    <td class="px-6 py-4 text-center">{{form[email]['name']}}</td>
                    <td class="px-6 py-4 text-center">{{form[email]['email']}}</td>
                    <td class="px-6 py-4 text-center">{{form[email]['message']}}</td>
                </tr>
            {% endfor %}
        {% endif %}
        </table>
        <a href='/contact_us' class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 ml-0 mr-2 sm:mt-0">Back to Contact Us</a>
    </div>
    </div>
  </section>
{% endblock %}

BlogApp/templates/general/ssr.html
{% extends "base.html" %}
{% block title %} Contact Us {% endblock %}
{% block body %} 
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-center mx-auto">
        {% if not form %}
        <p class="flex-grow sm:pr-16 text-xl font-medium title-font text-gray-800">No data available yet!</p>
        {% else %}
        <table class='relative w-full border overflow-auto mr-12'>
            <caption>Newsletter subscription form data-entry table</caption>
            <tr>
                <th class="sticky top-0 px-6 py-3 text-red-900 bg-red-300">Email</th>
            </tr>
            {% for i in form %}
                <tr class="divide-y bg-red-100 hover:bg-red-200">
                    <td class="px-6 py-4 text-center">{{i}}</td>
                </tr>
            {% endfor %}
        {% endif %}
        </table>
        <a href='/' class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 mr-2 sm:mt-0">Back to Home</a>
    </div>
    </div>
  </section>
{% endblock %}

BlogApp/templates/general/studyhome.html
{% extends 'base.html' %}

{% block body %}
{% for item in tools %}
<div class="p-4 lg:w-/3">
    <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
      <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">{{  item.title  }}</h1>
      <p class="leading-relaxed mb-3">{{  item.description  }}</p>
      <a href='/studytools/{{item.url}}' class="text-red-500 inline-flex items-center">Go</a>
        <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path d="M5 12h14"></path>
          <path d="M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </div>

  {% endfor %}

  {% endblock %}

BlogApp/templates/general/tbfy.html
{% extends "base.html" %}
{% block title %} Dead-End {% endblock %}
{% block body %} 
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
        <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">This part of the website is still in development...We apologise for any inconvenience caused!</h1>
        <a href='/' class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Back to Home</a>
        <a href="javascript:close_window();" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 ml-10 sm:mt-0">Or close this tab</a>
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}
<script>
function close_window() {
  if (confirm("Close this Tab?")) {
    close();
  }
}
</script>
{% endblock %}